server:
  port: 8082
spring:
  application:
    name: Customer
  datasource:
    url: jdbc:mysql://localhost:3306/spr240
    username: root
    password: Imaaz
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
